Repository BroadleafCommerce/DemoSite, pull requests merged in 2020-06, with the labels that each got.

#62 Fix update cache time
  admin/src/main/resources/bl-override-ehcache-admin.xml
  site/src/main/resources/bl-override-ehcache.xml
Labels: severity-minor, type-bug

#64 Add Solr Reindex to community
  admin/src/main/java/com/community/admin/web/AdminSolrReindexController.java
  admin/src/main/resources/community-demo-style/templates/admin/community_indexer.html
  core/src/main/java/com/community/core/config/CoreConfig.java
  core/src/main/resources/sql/load_solr_reindex_community.sql
Labels: type-feature

#65 Remove internal SessionFixationProtectionFilter
  core/src/main/resources/runtime-properties/common-shared.properties
  site/src/main/java/com/community/configuration/SiteSecurityConfig.java
Labels: severity-minor, type-enhancement

#70 Remove blc:googleExpreiments from refernce
  site/src/main/resources/webTemplates/layout/partials/head.html
Labels: severity-minor, type-bug
